name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  app-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: jest --apikey=${{ secrets.MD_API_KEY }}
    - run: npm run prepare
    - uses: ./
      with:
        file: './mosaic-data/schema.json'
        api-key: ${{ secrets.MD_API_KEY }}
